[pytest]
pythonpath = .
# Enable auto-detection of the appropriate asyncio mode based on the environment
asyncio_mode = auto
# Set the default scope for the asyncio event loop fixture to 'function' to ensure a fresh loop for each test
asyncio_default_fixture_loop_scope = function